//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GameStore.Web.PaymentService
{


    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PaymentParams", Namespace="http://schemas.datacontract.org/2004/07/GameStore.WcfService.Models")]
    [System.SerializableAttribute()]
    public partial class PaymentParams : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private decimal AmountField;
        
        private int CvvCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmailField;
        
        private int ExpirationMonthField;
        
        private int ExpirationYearField;
        
        private string FromCardNumberField;
        
        private string NameSurnameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PhoneNumberField;
        
        private string PurposeField;
        
        private string ToCardNumberField;
        
        private string TokenField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public decimal Amount {
            get {
                return this.AmountField;
            }
            set {
                if ((this.AmountField.Equals(value) != true)) {
                    this.AmountField = value;
                    this.RaisePropertyChanged("Amount");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int CvvCode {
            get {
                return this.CvvCodeField;
            }
            set {
                if ((this.CvvCodeField.Equals(value) != true)) {
                    this.CvvCodeField = value;
                    this.RaisePropertyChanged("CvvCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Email {
            get {
                return this.EmailField;
            }
            set {
                if ((object.ReferenceEquals(this.EmailField, value) != true)) {
                    this.EmailField = value;
                    this.RaisePropertyChanged("Email");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int ExpirationMonth {
            get {
                return this.ExpirationMonthField;
            }
            set {
                if ((this.ExpirationMonthField.Equals(value) != true)) {
                    this.ExpirationMonthField = value;
                    this.RaisePropertyChanged("ExpirationMonth");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int ExpirationYear {
            get {
                return this.ExpirationYearField;
            }
            set {
                if ((this.ExpirationYearField.Equals(value) != true)) {
                    this.ExpirationYearField = value;
                    this.RaisePropertyChanged("ExpirationYear");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string FromCardNumber {
            get {
                return this.FromCardNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.FromCardNumberField, value) != true)) {
                    this.FromCardNumberField = value;
                    this.RaisePropertyChanged("FromCardNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string NameSurname {
            get {
                return this.NameSurnameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameSurnameField, value) != true)) {
                    this.NameSurnameField = value;
                    this.RaisePropertyChanged("NameSurname");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PhoneNumber {
            get {
                return this.PhoneNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.PhoneNumberField, value) != true)) {
                    this.PhoneNumberField = value;
                    this.RaisePropertyChanged("PhoneNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string Purpose {
            get {
                return this.PurposeField;
            }
            set {
                if ((object.ReferenceEquals(this.PurposeField, value) != true)) {
                    this.PurposeField = value;
                    this.RaisePropertyChanged("Purpose");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string ToCardNumber {
            get {
                return this.ToCardNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.ToCardNumberField, value) != true)) {
                    this.ToCardNumberField = value;
                    this.RaisePropertyChanged("ToCardNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string Token {
            get {
                return this.TokenField;
            }
            set {
                if ((object.ReferenceEquals(this.TokenField, value) != true)) {
                    this.TokenField = value;
                    this.RaisePropertyChanged("Token");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PaymentStatus", Namespace="http://schemas.datacontract.org/2004/07/GameStore.WcfService.Enums")]
    public enum PaymentStatus : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Succesful = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        NotEnoughMoney = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        CardDoesnotExist = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Failed = 3,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Transfer", Namespace="http://schemas.datacontract.org/2004/07/GameStore.WcfService.Models")]
    [System.SerializableAttribute()]
    public partial class Transfer : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal AmountOfTransferField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime DateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FromCardNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PurposeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SecureCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private GameStore.Web.PaymentService.PaymentStatus StatusField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ToCardNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Guid TransferIdField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal AmountOfTransfer {
            get {
                return this.AmountOfTransferField;
            }
            set {
                if ((this.AmountOfTransferField.Equals(value) != true)) {
                    this.AmountOfTransferField = value;
                    this.RaisePropertyChanged("AmountOfTransfer");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime Date {
            get {
                return this.DateField;
            }
            set {
                if ((this.DateField.Equals(value) != true)) {
                    this.DateField = value;
                    this.RaisePropertyChanged("Date");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FromCardNumber {
            get {
                return this.FromCardNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.FromCardNumberField, value) != true)) {
                    this.FromCardNumberField = value;
                    this.RaisePropertyChanged("FromCardNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Purpose {
            get {
                return this.PurposeField;
            }
            set {
                if ((object.ReferenceEquals(this.PurposeField, value) != true)) {
                    this.PurposeField = value;
                    this.RaisePropertyChanged("Purpose");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SecureCode {
            get {
                return this.SecureCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.SecureCodeField, value) != true)) {
                    this.SecureCodeField = value;
                    this.RaisePropertyChanged("SecureCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public GameStore.Web.PaymentService.PaymentStatus Status {
            get {
                return this.StatusField;
            }
            set {
                if ((this.StatusField.Equals(value) != true)) {
                    this.StatusField = value;
                    this.RaisePropertyChanged("Status");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ToCardNumber {
            get {
                return this.ToCardNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.ToCardNumberField, value) != true)) {
                    this.ToCardNumberField = value;
                    this.RaisePropertyChanged("ToCardNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid TransferId {
            get {
                return this.TransferIdField;
            }
            set {
                if ((this.TransferIdField.Equals(value) != true)) {
                    this.TransferIdField = value;
                    this.RaisePropertyChanged("TransferId");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="PaymentService.IPaymentService")]
    public interface IPaymentService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPaymentService/AuthorizeUser", ReplyAction="http://tempuri.org/IPaymentService/AuthorizeUserResponse")]
        GameStore.Web.PaymentService.AuthorizeUserResponse AuthorizeUser(GameStore.Web.PaymentService.AuthorizeUserRequest request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPaymentService/AuthorizeUser", ReplyAction="http://tempuri.org/IPaymentService/AuthorizeUserResponse")]
        System.Threading.Tasks.Task<GameStore.Web.PaymentService.AuthorizeUserResponse> AuthorizeUserAsync(GameStore.Web.PaymentService.AuthorizeUserRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPaymentService/PayByVisa", ReplyAction="http://tempuri.org/IPaymentService/PayByVisaResponse")]
        GameStore.Web.PaymentService.PaymentStatus PayByVisa(GameStore.Web.PaymentService.PaymentParams data);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPaymentService/PayByVisa", ReplyAction="http://tempuri.org/IPaymentService/PayByVisaResponse")]
        System.Threading.Tasks.Task<GameStore.Web.PaymentService.PaymentStatus> PayByVisaAsync(GameStore.Web.PaymentService.PaymentParams data);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPaymentService/PayByMasterCard", ReplyAction="http://tempuri.org/IPaymentService/PayByMasterCardResponse")]
        GameStore.Web.PaymentService.PaymentStatus PayByMasterCard(GameStore.Web.PaymentService.PaymentParams data);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPaymentService/PayByMasterCard", ReplyAction="http://tempuri.org/IPaymentService/PayByMasterCardResponse")]
        System.Threading.Tasks.Task<GameStore.Web.PaymentService.PaymentStatus> PayByMasterCardAsync(GameStore.Web.PaymentService.PaymentParams data);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPaymentService/Confirm", ReplyAction="http://tempuri.org/IPaymentService/ConfirmResponse")]
        GameStore.Web.PaymentService.PaymentStatus Confirm(System.Guid transferId, string secureCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPaymentService/Confirm", ReplyAction="http://tempuri.org/IPaymentService/ConfirmResponse")]
        System.Threading.Tasks.Task<GameStore.Web.PaymentService.PaymentStatus> ConfirmAsync(System.Guid transferId, string secureCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPaymentService/GetHistoryByCard", ReplyAction="http://tempuri.org/IPaymentService/GetHistoryByCardResponse")]
        GameStore.Web.PaymentService.Transfer[] GetHistoryByCard(string cardNumber);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPaymentService/GetHistoryByCard", ReplyAction="http://tempuri.org/IPaymentService/GetHistoryByCardResponse")]
        System.Threading.Tasks.Task<GameStore.Web.PaymentService.Transfer[]> GetHistoryByCardAsync(string cardNumber);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="AuthorizeUser", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class AuthorizeUserRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string email;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string password;
        
        public AuthorizeUserRequest() {
        }
        
        public AuthorizeUserRequest(string email, string password) {
            this.email = email;
            this.password = password;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="AuthorizeUserResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class AuthorizeUserResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public bool AuthorizeUserResult;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string token;
        
        public AuthorizeUserResponse() {
        }
        
        public AuthorizeUserResponse(bool AuthorizeUserResult, string token) {
            this.AuthorizeUserResult = AuthorizeUserResult;
            this.token = token;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IPaymentServiceChannel : GameStore.Web.PaymentService.IPaymentService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class PaymentServiceClient : System.ServiceModel.ClientBase<GameStore.Web.PaymentService.IPaymentService>, GameStore.Web.PaymentService.IPaymentService {
        
        public PaymentServiceClient() {
        }
        
        public PaymentServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public PaymentServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PaymentServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PaymentServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        GameStore.Web.PaymentService.AuthorizeUserResponse GameStore.Web.PaymentService.IPaymentService.AuthorizeUser(GameStore.Web.PaymentService.AuthorizeUserRequest request) {
            return base.Channel.AuthorizeUser(request);
        }
        
        public bool AuthorizeUser(string email, string password, out string token) {
            GameStore.Web.PaymentService.AuthorizeUserRequest inValue = new GameStore.Web.PaymentService.AuthorizeUserRequest();
            inValue.email = email;
            inValue.password = password;
            GameStore.Web.PaymentService.AuthorizeUserResponse retVal = ((GameStore.Web.PaymentService.IPaymentService)(this)).AuthorizeUser(inValue);
            token = retVal.token;
            return retVal.AuthorizeUserResult;
        }
        
        public System.Threading.Tasks.Task<GameStore.Web.PaymentService.AuthorizeUserResponse> AuthorizeUserAsync(GameStore.Web.PaymentService.AuthorizeUserRequest request) {
            return base.Channel.AuthorizeUserAsync(request);
        }
        
        public GameStore.Web.PaymentService.PaymentStatus PayByVisa(GameStore.Web.PaymentService.PaymentParams data) {
            return base.Channel.PayByVisa(data);
        }
        
        public System.Threading.Tasks.Task<GameStore.Web.PaymentService.PaymentStatus> PayByVisaAsync(GameStore.Web.PaymentService.PaymentParams data) {
            return base.Channel.PayByVisaAsync(data);
        }
        
        public GameStore.Web.PaymentService.PaymentStatus PayByMasterCard(GameStore.Web.PaymentService.PaymentParams data) {
            return base.Channel.PayByMasterCard(data);
        }
        
        public System.Threading.Tasks.Task<GameStore.Web.PaymentService.PaymentStatus> PayByMasterCardAsync(GameStore.Web.PaymentService.PaymentParams data) {
            return base.Channel.PayByMasterCardAsync(data);
        }
        
        public GameStore.Web.PaymentService.PaymentStatus Confirm(System.Guid transferId, string secureCode) {
            return base.Channel.Confirm(transferId, secureCode);
        }
        
        public System.Threading.Tasks.Task<GameStore.Web.PaymentService.PaymentStatus> ConfirmAsync(System.Guid transferId, string secureCode) {
            return base.Channel.ConfirmAsync(transferId, secureCode);
        }
        
        public GameStore.Web.PaymentService.Transfer[] GetHistoryByCard(string cardNumber) {
            return base.Channel.GetHistoryByCard(cardNumber);
        }
        
        public System.Threading.Tasks.Task<GameStore.Web.PaymentService.Transfer[]> GetHistoryByCardAsync(string cardNumber) {
            return base.Channel.GetHistoryByCardAsync(cardNumber);
        }
    }
}
